<?php

/**
 * @file
 * Contains Drupal\chado_entity\chado_entity.module.
 */

/**
 * @defgroup chado_entity Example: Content Entity
 * @ingroup examples
 * @{
 * Implement a content entity.
 *
 * This module demonstrates implementing a content entity.
 *
 * Entity API is the API that stores pieces of content and configuration for
 * Drupal core. For instance, if you've encountered node content types, you've
 * encountered entities of type 'node.'
 *
 * This example implements the Entity API so that we have an entity type usable
 * by the user which you might think of as specialized nodes, but which are
 * different from nodes. These entities are called Chado entities, and are known
 * internally by the machine name chado_entity.
 *
 * Chado entity is a fieldable content entity used to hold structured information
 * without the overhead of using a node content type. 'Fieldable' means you can
 * attach fields to it, like you can with nodes. It is defined programmatically
 * (completely in code). We will show the main techniques to handle and expose
 * the contents of this entity type.
 *
 * The Chado entity will demonstrate the main tasks for an entity:
 * - define
 * - save
 * - load
 * - view
 * - edit
 * - delete
 * - control access
 *
 * Where ever possible, we use the amazing tools built into D8 natively.
 *
 * @see Drupal\chado_entity\Entity\ChadoEntity
 * }
 */

/**
 * Implements hook_entity_type_alter().
 */
function chado_entity_type_alter(array &$entity_types)
{
  $entity_types['node']->setHandlerClass('storage', 'Drupal\chado_entity\NodeStorage');
}
